name: Zig Build

on: 
  push:
    paths:
      - '.github/workflows/zig_build.yml'
      - 'src/*'
      - 'test.sh'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: goto-bus-stop/setup-zig@v2.0.1
          with:
            version: master
        - run: zig build
        - run: sh ./test.sh
